# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: pack

on:
  push:
    tags:
      - 'v*'  # Ex: v1.0.0
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Buid an example project
      run: |
        dotnet new install .\
        dotnet new mudblazor-server-solution -n AppName -o ./app
        dotnet build ./app/AppName.sln
    - name: pack
      run: dotnet pack --output ./nupkg
      
    - name: Push to nuget
      run: dotnet nuget push ./nupkg/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}

