name: test-template

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test-template:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Test template build
        run: |
          dotnet new install .\
          dotnet new mudblazor-server-solution -n AppName -o ./app
          dotnet build ./app/AppName.sln
